//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelitas.Proyecto.ArticulosPerdidos.Model
{
     using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class C__MigrationHistory
    {
        [DataMember] public string MigrationId { get; set; }
        [DataMember] public string ContextKey { get; set; }
        [DataMember] public byte[] Model { get; set; }
        [DataMember] public string ProductVersion { get; set; }
    }
}
