//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelitas.Proyecto.ArticulosPerdidos.Model
{
     using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class PERSONA_REPORTANDO_EXTRAVIO
    {
        [DataMember] public int ID { get; set; }
        [DataMember] public Nullable<int> ID_PERSONA { get; set; }
        [DataMember] public Nullable<int> ID_CATEGORIA { get; set; }
        [DataMember] public Nullable<System.DateTime> FECHA_REPORTE { get; set; }
    
        public virtual CATEGORIA_ARTICULO CATEGORIA_ARTICULO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
