USE [master]
GO

/****** Object:  Database [ProyectoProgra5]    Script Date: 11/28/2018 11:56:52 PM ******/
CREATE DATABASE [ProyectoProgra5]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProyectoProgra5', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ProyectoProgra5.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProyectoProgra5_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ProyectoProgra5_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ProyectoProgra5] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProyectoProgra5].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProyectoProgra5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProyectoProgra5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProyectoProgra5] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET RECOVERY FULL 
GO

ALTER DATABASE [ProyectoProgra5] SET  MULTI_USER 
GO

ALTER DATABASE [ProyectoProgra5] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProyectoProgra5] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProyectoProgra5] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProyectoProgra5] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProyectoProgra5] SET QUERY_STORE = OFF
GO

USE [ProyectoProgra5]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ProyectoProgra5] SET  READ_WRITE 
GO


USE [ProyectoProgra5]
GO

/****** Object:  Table [dbo].[ARTICULOS]    Script Date: 11/28/2018 11:57:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ARTICULOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TIPO] [varchar](50) NULL,
	[MARCA] [varchar](50) NULL,
	[MODELO] [varchar](50) NULL,
	[NUMSERIE] [varchar](50) NULL,
	[CATEGORIA] [varchar](50) NULL,
	[SUBCATEGORIA] [varchar](50) NULL,
	[ESTADO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[IDPERSONAENTREGADO] [int] NULL,
	[IDPERSONADEVUELTO] [int] NULL,
	[IDPERSONAREPORTADO] [int] NULL,
	[FECHAREPORTADO] [datetime] NULL,
	[FECHAENTREGADO] [datetime] NULL,
	[FECHADEVUELTO] [datetime] NULL,
 CONSTRAINT [PK_ARTICULOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ARTICULOS]  WITH CHECK ADD  CONSTRAINT [FK_ARTICULOSIDDEVUELTO_IDPERSONA] FOREIGN KEY([IDPERSONADEVUELTO])
REFERENCES [dbo].[PERSONAS] ([IDPERSONA])
GO

ALTER TABLE [dbo].[ARTICULOS] CHECK CONSTRAINT [FK_ARTICULOSIDDEVUELTO_IDPERSONA]
GO

ALTER TABLE [dbo].[ARTICULOS]  WITH CHECK ADD  CONSTRAINT [FK_ARTICULOSIDENTREGA_PERSONA] FOREIGN KEY([IDPERSONAENTREGADO])
REFERENCES [dbo].[PERSONAS] ([IDPERSONA])
GO

ALTER TABLE [dbo].[ARTICULOS] CHECK CONSTRAINT [FK_ARTICULOSIDENTREGA_PERSONA]
GO

ALTER TABLE [dbo].[ARTICULOS]  WITH CHECK ADD  CONSTRAINT [FK_ARTICULOSIDREPORT_IDPERSONA] FOREIGN KEY([IDPERSONAREPORTADO])
REFERENCES [dbo].[PERSONAS] ([IDPERSONA])
GO

ALTER TABLE [dbo].[ARTICULOS] CHECK CONSTRAINT [FK_ARTICULOSIDREPORT_IDPERSONA]
GO


USE [ProyectoProgra5]
GO

/****** Object:  Table [dbo].[PERSONAS]    Script Date: 11/28/2018 11:57:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSONAS](
	[IDPERSONA] [int] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[APELLIDOS] [varchar](100) NULL,
	[TELEFONO] [int] NULL,
	[CORREO] [varchar](50) NULL,
	[TIPOINTERACCION] [varchar](50) NULL,
	[PUESTO] [varchar](50) NULL,
 CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED 
(
	[IDPERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


