--
--Creacion de la Base de datos PROYECTOPROGRA5
--
USE [master]
GO

/****** Object:  Database [ProyectoProgra5]    Script Date: 12/4/2018 11:26:45 PM ******/
CREATE DATABASE [ProyectoProgra5]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProyectoProgra5', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ProyectoProgra5.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProyectoProgra5_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ProyectoProgra5_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ProyectoProgra5] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProyectoProgra5].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProyectoProgra5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProyectoProgra5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProyectoProgra5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProyectoProgra5] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET RECOVERY FULL 
GO

ALTER DATABASE [ProyectoProgra5] SET  MULTI_USER 
GO

ALTER DATABASE [ProyectoProgra5] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProyectoProgra5] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProyectoProgra5] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProyectoProgra5] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProyectoProgra5] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProyectoProgra5] SET QUERY_STORE = OFF
GO

USE [ProyectoProgra5]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ProyectoProgra5] SET  READ_WRITE 
GO

--
--Creacion de la tabla  ARTICULOS
--
USE [ProyectoProgra5]
GO

/****** Object:  Table [dbo].[ARTICULOS]    Script Date: 12/4/2018 11:27:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ARTICULOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CATEGORIA] [int] NULL,
	[ESTADO] [varchar](30) NULL,
	[MARCA] [varchar](50) NULL,
	[MODELO] [varchar](30) NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[FOTOS] [varchar](250) NULL,
 CONSTRAINT [PK_ARTICULOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
--
--Creacion de la tabla  CATEGORIA_ARTICULO
--
USE [ProyectoProgra5]
GO

/****** Object:  Table [dbo].[CATEGORIA_ARTICULO]    Script Date: 12/4/2018 11:28:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORIA_ARTICULO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_CATEGORIA] [varchar](30) NULL,
	[SUBCATEGORIA] [varchar](30) NULL,
 CONSTRAINT [PK_CATEGORIA_ARTICULO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
--
--Creacion de la tabla  PERSONA
--
USE [ProyectoProgra5]
GO

/****** Object:  Table [dbo].[PERSONA]    Script Date: 12/4/2018 11:29:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSONA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_COMPLETO] [varchar](200) NULL,
	[USUARIO] [varchar](30) NULL,
	[PASSWORD] [varchar](30) NULL,
	[EMAIL] [varchar](50) NULL,
	[ROL] [varchar](30) NULL,
 CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
--
--Creacion de la tabla  PERSONA_ENTREGANDO
--
USE [ProyectoProgra5]
GO

/****** Object:  Table [dbo].[PERSONA_ENTREGANDO]    Script Date: 12/4/2018 11:30:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSONA_ENTREGANDO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERSONA] [int] NULL,
	[ID_ARTICULO] [int] NULL,
	[FECHA_ENTREGA] [datetime] NULL,
 CONSTRAINT [PK_PERSONA_ENTREGANDO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
--
--Creacion de la tabla  PERSONA_REPORTANDO_EXTRAVIO
--
USE [ProyectoProgra5]
GO

/****** Object:  Table [dbo].[PERSONA_REPORTANDO_EXTRAVIO]    Script Date: 12/4/2018 11:30:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSONA_REPORTANDO_EXTRAVIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERSONA] [int] NULL,
	[ID_CATEGORIA] [int] NULL,
	[FECHA_REPORTE] [datetime] NULL,
 CONSTRAINT [PK_PERSONA_REPORTANDO_EXTRAVIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



--Se agregan los FK a las tablas y se crean las relaciones.

ALTER TABLE [dbo].[PERSONA_REPORTANDO_EXTRAVIO]  WITH CHECK ADD  CONSTRAINT [FK_PERSONA_REPORTANDO_EXTRAVIO_CATEGORIA] FOREIGN KEY([ID_CATEGORIA])
REFERENCES [dbo].[CATEGORIA_ARTICULO] ([ID])
GO

ALTER TABLE [dbo].[PERSONA_REPORTANDO_EXTRAVIO] CHECK CONSTRAINT [FK_PERSONA_REPORTANDO_EXTRAVIO_CATEGORIA]
GO

ALTER TABLE [dbo].[PERSONA_REPORTANDO_EXTRAVIO]  WITH CHECK ADD  CONSTRAINT [FK_PERSONA_REPORTANDO_EXTRAVIO_PERSONA] FOREIGN KEY([ID_PERSONA])
REFERENCES [dbo].[PERSONA] ([ID])
GO

ALTER TABLE [dbo].[PERSONA_REPORTANDO_EXTRAVIO] CHECK CONSTRAINT [FK_PERSONA_REPORTANDO_EXTRAVIO_PERSONA]
GO

ALTER TABLE [dbo].[PERSONA_ENTREGANDO]  WITH CHECK ADD  CONSTRAINT [FK_PERSONA_ENTREGANDO_ARTICULO] FOREIGN KEY([ID_ARTICULO])
REFERENCES [dbo].[ARTICULOS] ([ID])
GO

ALTER TABLE [dbo].[PERSONA_ENTREGANDO] CHECK CONSTRAINT [FK_PERSONA_ENTREGANDO_ARTICULO]
GO

ALTER TABLE [dbo].[PERSONA_ENTREGANDO]  WITH CHECK ADD  CONSTRAINT [FK_PERSONA_ENTREGANDO_PERSONA] FOREIGN KEY([ID_PERSONA])
REFERENCES [dbo].[PERSONA] ([ID])
GO

ALTER TABLE [dbo].[PERSONA_ENTREGANDO] CHECK CONSTRAINT [FK_PERSONA_ENTREGANDO_PERSONA]
GO


ALTER TABLE [dbo].[ARTICULOS]  WITH CHECK ADD  CONSTRAINT [FK_ARTICULOS_CATEGORIA] FOREIGN KEY([ID_CATEGORIA])
REFERENCES [dbo].[CATEGORIA_ARTICULO] ([ID])
GO

ALTER TABLE [dbo].[ARTICULOS] CHECK CONSTRAINT [FK_ARTICULOS_CATEGORIA]
GO


--Insertr datos en las tablas creadas. 

INSERT INTO PERSONA(NOMBRE_COMPLETO, USUARIO, PASSWORD, EMAIL, ROL) VALUES('Micky Heskins','mheskins0','dYyBF3zk0r','mheskins0@acquirethisname.com','Invitado');
INSERT INTO PERSONA(NOMBRE_COMPLETO, USUARIO, PASSWORD, EMAIL, ROL) VALUES('Kippy Polleye','kpolleye1','Ks0kMmCoUN','kpolleye1@google.cn','Admin');
INSERT INTO PERSONA(NOMBRE_COMPLETO, USUARIO, PASSWORD, EMAIL, ROL) VALUES('Addy Neath','aneath2','21f6btWs5z','aneath2@latimes.com','Custodia');
INSERT INTO PERSONA(NOMBRE_COMPLETO, USUARIO, PASSWORD, EMAIL, ROL) VALUES('Myron Barbour','mbarbour3','MADcCEVwpN','mbarbour3@g.co','Invitado');
INSERT INTO PERSONA(NOMBRE_COMPLETO, USUARIO, PASSWORD, EMAIL, ROL) VALUES('Dare Sprowle','dsprowle4','YqlwsdV','dsprowle4@rakuten.co.jp','Custodia');
INSERT INTO CATEGORIA_ARTICULO(NOMBRE_CATEGORIA, SUBCATEGORIA) VALUES('ELECTRONICOS', 'COMPUTADORAS');
INSERT INTO CATEGORIA_ARTICULO(NOMBRE_CATEGORIA, SUBCATEGORIA) VALUES('UNIVERSITARIOS', 'EQUIPO DE OFICINA');
INSERT INTO CATEGORIA_ARTICULO(NOMBRE_CATEGORIA, SUBCATEGORIA) VALUES('PERSONALES', 'UTILES');
INSERT INTO CATEGORIA_ARTICULO(NOMBRE_CATEGORIA, SUBCATEGORIA) VALUES('PERSONALES', 'DOCUMENTOS');
INSERT INTO CATEGORIA_ARTICULO(NOMBRE_CATEGORIA, SUBCATEGORIA) VALUES('ELECTRONICOS', 'CELULARES');
INSERT INTO ARTICULOS(ID_CATEGORIA, MARCA, MODELO, DESCRIPCION, FOTOS) VALUES(1, 'DELL', 'E7570', 'Computadora portatil', 'https://images-na.ssl-images-amazon.com/images/I/615V3AqK%2B1L._SX679_.jpg');
INSERT INTO ARTICULOS(ID_CATEGORIA, MARCA, MODELO, DESCRIPCION, FOTOS) VALUES(2, 'HP', 'gp70', 'Proyector', 'https://i.linio.com/p/dd463041cf61163b2a9d3fca86e4134b-product.jpg');
INSERT INTO ARTICULOS(ID_CATEGORIA, MARCA, MODELO, DESCRIPCION, FOTOS) VALUES(3, 'Norma', 'Cuaderno', 'Cuaderno de apuntes', 'http://www.oficomercr.com/1111-large_default/cuaderno-resorte-carta-80-hojas-norma.jpg');
INSERT INTO ARTICULOS(ID_CATEGORIA, MARCA, MODELO, DESCRIPCION, FOTOS) VALUES(4, 'Visa', 'Tarjeta', 'Tarjeta de debito', 'https://www.baccredomatic.com/sites/default/files/visa-09.jpg');
INSERT INTO ARTICULOS(ID_CATEGORIA, MARCA, MODELO, DESCRIPCION, FOTOS) VALUES(5, 'Samsung', 's9', 'Celular negro', 'https://ksassets.timeincuk.net/wp/uploads/sites/54/2018/02/DSCF0155-1920x1280.jpg');
INSERT INTO PERSONA_ENTREGANDO(ID_PERSONA, ID_ARTICULO, FECHA_ENTREGA) VALUES(1, 1, 23/11/18);
INSERT INTO PERSONA_ENTREGANDO(ID_PERSONA, ID_ARTICULO, FECHA_ENTREGA) VALUES(2, 2, 2/09/18);
INSERT INTO PERSONA_ENTREGANDO(ID_PERSONA, ID_ARTICULO, FECHA_ENTREGA) VALUES(4, 5, 23/11/18);
INSERT INTO PERSONA_REPORTANDO_EXTRAVIO(ID_PERSONA, ID_CATEGORIA, FECHA_REPORTE) VALUES(3, 1, 02/05/17);
INSERT INTO PERSONA_REPORTANDO_EXTRAVIO(ID_PERSONA, ID_CATEGORIA, FECHA_REPORTE) VALUES(5, 4, 31/02/15);